### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by always91** [RedEM-RP/redemrp_identity#14]
bug 1 : new character = freeze screen
bug 2 : invisible character
bug 3  : clothing I press but nothing happens

however great job I hope it will be fixed :)

**Comment by kanersps** [comment]
Still an issue with latest push?

**Comment by IllInuz** [comment]
yes @kanersps 
https://prnt.sc/tcfpir

**Comment by always91** [comment]
no, now worked perfect :)

**Comment by daniilkas12345** [comment]
> Все еще проблема с последним толчком?

Почему персонажи невидимые ?

**Comment by Nastrix** [comment]
Issue is still occuring. Invisible Characters

**Comment by xDeadGuy69x** [comment]
The invisible characters usually occurs when the skin tone if different from the default

**Comment by amakuu** [comment]
HDD --> SSD
