### ISSUE TITLE
Infinite loading characters

### ISSUE THREAD

**Issue by MikMikYT** [RedEM-RP/redemrp_identity#19]
I am hosting a server on my pc. 
Without characters or skin script it runs good, I can join the server and play, but when I make a character and try to log in back in-game "Loading characters" screen appears and it just loads infinitely. 
Do you maybe know what is the issue? Thanks in advance!

**Comment by Megamaluco** [comment]
Also, have the same problem, did you manage to fix it?

**Comment by amakuu** [comment]
If its stay infinitely, it means that the error in db occurs and characters are not loaded properly. Clear your db and try again.
/close

**Comment by zandercillo94** [comment]
> 

I have installed more than 4 times today the error continues
1SCRIPT ERROR: @redemrp_identity/client/cl_main.lua:90: bad argument #1 to 'for iterator' (table expected, got nil)
![unknown (2)](https://user-images.githubusercontent.com/107600302/173987053-9963bb63-529f-49ee-a176-9890d22b4cdd.png)

**Comment by Wollffus** [comment]
Check your ensure order. Reference this server config. https://github.com/Wollffus/RedEM_PreBuild
