### ISSUE TITLE
No Menu or Character Upon Server Join

### ISSUE THREAD

**Issue by Peekofwar** [RedEM-RP/redemrp_identity#21]
Not sure what's happening, but it seems there's a problem with MySQL... When I load into the server, all I see is a camera angle of some random part of the world. No menu, and no character. 

![20210302205051_1](https://user-images.githubusercontent.com/10189526/109740245-d6382980-7b7f-11eb-8f17-139999c005c3.jpg)

In some of your other resources, you mention insertting an SQL into a database, but you don't elaborate on what that means.

```
(client) RedEM: Player activated: Peekofwar
[ERROR] [MySQL] [esplugin_mysql] An error happens on MySQL for query "SELECT 1 FROM users WHERE `identifier`='steam:11000010bbe70ba';": getaddrinfo ENOTFOUND ip
SCRIPT ERROR: @esplugin_mysql/server.lua:6: attempt to index a nil value (local 'users')
> ref (@esplugin_mysql/server.lua:6)
>  (@mysql-async/mysql-async.js:14431)
[ERROR] [MySQL] [redemrp_identity] An error happens on MySQL for query "SELECT * FROM characters WHERE `identifier`='steam:11000010bbe70ba';": getaddrinfo ENOTFOUND ip
[ERROR] [MySQL] [redemrp_identity] An error happens on MySQL for query "SELECT * FROM skins WHERE `identifier`='steam:11000010bbe70ba';": getaddrinfo ENOTFOUND ip
[ERROR] [MySQL] [redemrp_identity] An error happens on MySQL for query "SELECT * FROM clothes WHERE `identifier`='steam:11000010bbe70ba';": getaddrinfo ENOTFOUND ip
```

```
set es_enableCustomData 1
set mysql_connection_string "server=ip;uid=user_name;password=very_secure_password;database=redemrp"
ensure esplugin_mysql
ensure mysql-async
ensure redem
ensure redem_roleplay

ensure pNotify

ensure redemrp_menu_base
ensure redemrp_inventory
ensure redemrp_clothing
ensure redemrp_identity
ensure redemrp_skin
ensure redemrp_respawn
ensure redemrp_shops-main
```
[log.txt](https://github.com/RedEM-RP/redemrp_identity/files/6073117/log.txt)

**Comment by Peekofwar** [comment]
> You have problem with your db config.

What is that, and how do I correct it?

**Comment by amakuu** [comment]
it seems that ip in config is wrong.

**Comment by Josilv9632** [comment]
> > You have problem with your db config.
> 
> What is that, and how do I correct it?

If you use MySQL you need to change those next values:

"server=ip;uid=user_name;password=very_secure_password;database=redemrp"

server=ip => server=127.0.0.1 OR server=localhost OR server=yourSQLserverAddressIP
uid=user_name => your MySQL username like e.g. uid=root OR uid=redmuser
password=very_secure_password => your mysql username above password, password=12345789pass_?
database=redemrp => If you alread have one with different name you should change it like database=myDBname

Remember for you to know all this values for your configuration, you need to pre install you mysql server or buy it or even request those configs from any server host admin.

**Comment by Peekofwar** [comment]
I did not hit close.

--

"...you need to pre install you mysql server..." So I also need to be running an SQL service along side the RedM server, or am I misunderstanding what you're saying?

**Comment by monkofnothing** [comment]
Yep busted.
ip address is fine config as far as i know is fine it does seem to be a Mysql thing apparently your supposed to do something with the Sql file what ever that is 


[ c-scripting-core] Creating script environments for _cfx_internal
[ citizen-server-impl] Scanning resources.
[ citizen-server-impl] Found 40 resources.
[ svadhesive] Authenticating server license key...
[ svadhesive] Server license key authentication succeeded. Welcome!
[ c-scripting-core] Creating script environments for yarn
[ citizen-server-impl] Started resource yarn
[ c-scripting-core] Creating script environments for sessionmanager-rdr3
[ citizen-server-impl] Started resource sessionmanager-rdr3
[ c-scripting-core] Creating script environments for mapmanager
[ citizen-server-impl] Started resource mapmanager
[ c-scripting-core] Creating script environments for webpack
[ citizen-server-impl] Started resource webpack
[ c-scripting-core] Creating script environments for chat
[ citizen-server-impl] Started resource chat
[ citizen-server-impl] Started resource spawnmanager
[ script:mapmanager] Started gametype Freeroam
[ citizen-server-impl] Started resource basic-gamemode
[ c-scripting-core] Creating script environments for hardcap
[ citizen-server-impl] Started resource hardcap
[ citizen-server-impl] Started resource loadingscreen
[ c-scripting-core] Creating script environments for mysql-async
[ citizen-server-impl] Started resource mysql-async
[ citizen-server-impl] Started resource interiors
[ c-scripting-core] Creating script environments for EasyAdmin
[ citizen-server-impl] Started resource EasyAdmin
[ c-scripting-core] Creating script environments for rconlog
[ citizen-server-impl] Started resource rconlog
[ citizen-server-impl] Couldn't find resource DokusCore.
[ c-resources-core] Could not find dependency redem for resource esplugin_mysql.
[ citizen-server-impl] Couldn't start resource esplugin_mysql.
[ citizen-server-impl] Couldn't find resource redem.
[ c-scripting-core] Creating script environments for redem_roleplay
[script:redem_rolepla] [RedEMRP] Entity created(0.97996674012392): npc NPC-01
[ citizen-server-impl] Started resource redem_roleplay
[ c-scripting-core] Creating script environments for redemrp_skin
[ citizen-server-impl] Started resource redemrp_skin
[ c-scripting-core] Creating script environments for redemrp_clothing
[ citizen-server-impl] Started resource redemrp_clothing
[ citizen-server-impl] Started resource redemrp_menu_base
[ c-scripting-core] Creating script environments for redemrp_identity
[ citizen-server-impl] Started resource redemrp_identity
[ c-scripting-core] Creating script environments for redemrp_respawn
[ citizen-server-impl] Started resource redemrp_respawn
[ citizen-server-impl] Couldn't find resource webadmin.
cfx&gt; [ script:EasyAdmin]
[ script:EasyAdmin] _______ _______ _______ __ __ _______ ______ _______ _____ __ _
[ script:EasyAdmin] |______ |_____| |______ \_/ |_____| | \ | | | | | \ |
[ script:EasyAdmin] |______ | | ______| | | | |_____/ | | | __|__ | \_|
[ script:EasyAdmin] Version 6.202
[ script:mapmanager] Started map redm-map-one
[ citizen-server-impl] Started resource redm-map-one
(node:52233) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:52233) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:52233) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:52233) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
(node:52233) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
(node:52233) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
[ script:mysql-async] [mysql-async] Database server connection established.
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "DROP DATABASE IF EXISTS `redemrp`;
[ script:mysql-async] CREATE DATABASE IF NOT EXISTS `redemrp`;
[ script:mysql-async] USE `redemrp`;
[ script:mysql-async]
[ script:mysql-async] CREATE TABLE IF NOT EXISTS `version` (
[ script:mysql-async] `id` int(11) NOT NULL,
[ script:mysql-async] `current` varchar(3) COLLATE utf8mb4_bin DEFAULT 'no',
[ script:mysql-async] PRIMARY KEY (`id`)
[ script:mysql-async] ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
[ script:mysql-async]
[ script:mysql-async] CREATE TABLE IF NOT EXISTS `characters` (
[ script:mysql-async] `identifier` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
[ script:mysql-async] `characterid` int(11) DEFAULT 0,
[ script:mysql-async] `money` int(11) DEFAULT 0,
[ script:mysql-async] `gold` int(11) DEFAULT 0,
[ script:mysql-async] `xp` int(11) DEFAULT 0,
[ script:mysql-async] `level` int(11) DEFAULT 0,
[ script:mysql-async] `job` varchar(50) COLLATE utf8mb4_bin DEFAULT 'unemployed',
[ script:mysql-async] `firstname` varchar(50) COLLATE utf8mb4_bin DEFAULT 'first',
[ script:mysql-async] `lastname` varchar(50) COLLATE utf8mb4_bin DEFAULT 'last',
[ script:mysql-async] `jobgrade` int(11) DEFAULT 0
[ script:mysql-async] ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
[ script:mysql-async]
[ script:mysql-async] CREATE TABLE IF NOT EXISTS `users` (
[ script:mysql-async] `identifier` varchar(50) COLLATE utf8mb4_bin NOT NULL,
[ script:mysql-async] `license` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
[ script:mysql-async] `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
[ script:mysql-async] `money` int(11) DEFAULT NULL,
[ script:mysql-async] `bank` int(11) DEFAULT NULL,
[ script:mysql-async] `permission_level` int(11) DEFAULT NULL,
[ script:mysql-async] `group` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
[ script:mysql-async] PRIMARY KEY (`identifier`)
[ script:mysql-async] ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
[ script:mysql-async] ": ER_DBACCESS_DENIED_ERROR: Access denied for user 'zap448093-2'@'%' to database 'redemrp'
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "INSERT INTO version(id, current) VALUES(1, 'yes');": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[script:redem_rolepla] [RedEM:RP] Database: Successfully created database
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "USE `redemrp`;
[ script:mysql-async]
[ script:mysql-async] ALTER TABLE `characters`
[ script:mysql-async] ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT FIRST,
[ script:mysql-async] ADD PRIMARY KEY (`id`);": ER_DBACCESS_DENIED_ERROR: Access denied for user 'zap448093-2'@'%' to database 'redemrp'
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "UPDATE version SET current='no' WHERE id=1": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "INSERT INTO version(id, current) VALUES(2, 'yes');": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[script:redem_rolepla] [RedEM:RP] Database: Successfully updated database for version: 2
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "USE `redemrp`;
[ script:mysql-async]
[ script:mysql-async] ALTER TABLE `version`
[ script:mysql-async] ADD COLUMN `resource` varchar(50),
[ script:mysql-async] DROP PRIMARY KEY;": ER_DBACCESS_DENIED_ERROR: Access denied for user 'zap448093-2'@'%' to database 'redemrp'
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "UPDATE version SET current='no' WHERE id=2": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "INSERT INTO version(id, current) VALUES(3, 'yes');": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[script:redem_rolepla] [RedEM:RP] Database: Successfully updated database for version: 3
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "USE `redemrp`;
[ script:mysql-async]
[ script:mysql-async] ALTER TABLE `characters`
[ script:mysql-async] ADD COLUMN `coords` VARCHAR(200) NULL DEFAULT '{}';": ER_DBACCESS_DENIED_ERROR: Access denied for user 'zap448093-2'@'%' to database 'redemrp'
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "UPDATE version SET current='no' WHERE id=3": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[ citizen-server-impl] fff
[ citizen-server-impl] cccc ff xx xx rr rr eee
[ citizen-server-impl] cc ffff xx rrr r ee e
[ citizen-server-impl] cc ff xx ... rr eeeee
[ citizen-server-impl] ccccc ff xx xx ... rr eeeee
[ citizen-server-impl]
[ citizen-server-impl] Authenticated with cfx.re Nucleus: https://zap-hosting-pqlpjy.users.cfx.re/
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "INSERT INTO version(id, current) VALUES(4, 'yes');": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[script:redem_rolepla] [RedEM:RP] Database: Successfully updated database for version: 4
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "USE `redemrp`;
[ script:mysql-async]
[ script:mysql-async] CREATE TABLE `web_permissions` (
[ script:mysql-async] `username` VARCHAR(50) NULL DEFAULT NULL,
[ script:mysql-async] `password` VARCHAR(50) NULL DEFAULT NULL,
[ script:mysql-async] `role` VARCHAR(50) NULL DEFAULT NULL
[ script:mysql-async] );": ER_DBACCESS_DENIED_ERROR: Access denied for user 'zap448093-2'@'%' to database 'redemrp'
[ citizen-server-impl] -- [server notice: tebex_not_set]
[ citizen-server-impl] ================
[ citizen-server-impl] Monetize your server using Tebex! Visit https://tebex.io/fivem for more info.
[ citizen-server-impl] ================
[ citizen-server-impl]
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "UPDATE version SET current='no' WHERE id=4": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "INSERT INTO version(id, current) VALUES(5, 'yes');": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[script:redem_rolepla] [RedEM:RP] Database: Successfully updated database for version: 5
[ script:mysql-async] [ERROR] [MySQL] [redem_roleplay] An error happens on MySQL for query "SELECT * FROM version WHERE current='yes'": ER_NO_SUCH_TABLE: Table 'zap448093-2.version' doesn't exist
[script:redem_rolepla] SCRIPT ERROR: @redem_roleplay/server/sv_db.lua:67: attempt to index a nil value (local '_version')
[script:redem_rolepla] &gt; ref (@redem_roleplay/server/sv_db.lua:67)
[script:redem_rolepla] &gt; &lt;unknown&gt; (@mysql-async/mysql-async.js:14431)
[ script:mysql-async]
[ script:hardcap] Connecting: someusername
[ script:mysql-async] [ERROR] [MySQL] [redemrp_identity] An error happens on MySQL for query "SELECT * FROM characters WHERE `identifier`='steam:11000010745e1c5';": ER_NO_SUCH_TABLE: Table 'zap448093-2.characters' doesn't exist
[ script:mysql-async] [ERROR] [MySQL] [redemrp_identity] An error happens on MySQL for query "SELECT * FROM skins WHERE `identifier`='steam:11000010745e1c5';": ER_NO_SUCH_TABLE: Table 'zap448093-2.skins' doesn't exist

**Comment by PatientXero** [comment]
Check your database console. Chances are that your redemrp.characters tables are not installed.

**Comment by Peekofwar** [comment]
> Check your database console. Chances are that your redemrp.characters tables are not installed.

"Database console?" So we do need to run a separate service.

**Comment by PatientXero** [comment]
I'd get some help from Zap. Sounds like they didn't install your artifacts correctly. First time run.sh is ran, it's supposed to populate a database called redemrp. That obviously didn't happen.

**Comment by Peekofwar** [comment]
> I'd get some help from Zap. Sounds like they didn't install your artifacts correctly. First time run.sh is ran, it's supposed to populate a database called redemrp. That obviously didn't happen.

I don't use Zap hosting. What is `run.sh`? Where should I get this from?

(I host all of my servers locally from my own physical hardware)\

**Comment by Peekofwar** [comment]
> > I'd get some help from Zap. Sounds like they didn't install your artifacts correctly. First time run.sh is ran, it's supposed to populate a database called redemrp. That obviously didn't happen.
> 
> I don't use Zap hosting. What is `run.sh`? Where should I get this from?
> 
> (I host all of my servers locally from my own physical hardware)\

PS: My machine is running Windows, not Linux.
