### ISSUE TITLE
Can't choose character 

### ISSUE THREAD

**Issue by BlueberryRP** [RedEM-RP/redemrp_identity#4]
When i just clear a cache and start server, than i already have a character, but can't chose any and have just create a new one.

**Comment by amakuu** [comment]
They are not stored in cache so its impossible.
Probably you have bad configuration (mysql).

**Comment by BlueberryRP** [comment]
> They are not stored in cache so its impossible.
> Probably you have bad configuration (mysql).

i just use db from redem_roleplay

**Comment by amakuu** [comment]
Ok, so when you create an Character it is writting into db? or no?

**Comment by BlueberryRP** [comment]
> Ok, so when you create an Character it is writting into db? or no?

Yes that is

**Comment by BlueberryRP** [comment]
> Ok, so when you create an Character it is writting into db? or no?

Every character isert into db, i have more then 10 chracters. Because when i just clear cache and restart server. I will make a new one because i can't choose anyone

**Comment by BlueberryRP** [comment]
There log file may be that will help:
[CitizenFX_log_2019-12-14T164700.log](https://github.com/RedEM-RP/redemrp_identity/files/3964058/CitizenFX_log_2019-12-14T164700.log)

**Comment by amakuu** [comment]
It won't.
It's nearly impossible what you describing.
When you don't have your characters listed - its means that they are not loaded from db
